### ISSUE TITLE
Compilation error: ESP8266WiFi.h: No such file or directory

### ISSUE THREAD

**Issue by Lordex-x** [dj1ch/minigotchi-ESP32#47]
At the time of compiling, it gives an error in .bin, warning that the file 'ESP8266WiFi.h' was not found.

I followed the installation step by step for the cardputer, with the minigotchi open in the Arduino IDE, I clicked on 'sketch' and 'export compiled binary'.

I expected a new executable .bin file to be generated. If I did something wrong, can you teach me?"

Let me know if there's anything else you'd like to know!

![imagem_2024-07-04_040005184](https://github.com/dj1ch/minigotchi-ESP32/assets/174689527/058be6cb-464e-4f93-a5b4-bff037aa6a8f)

**Comment by matrix224** [comment]
I think you downloaded the wrong repo.
There's two:

https://github.com/dj1ch/minigotchi
and 
https://github.com/dj1ch/minigotchi-ESP32

The first one is for ESP8266 boards, and the second one (the repo this issue is posted on) is for ESP32. It looks like you downloaded the ESP8266 one, but you want the ESP32 one.

Try downloading the source from this repo and trying with that instead

**Comment by Lordex-x** [comment]
> I think you downloaded the wrong repo.
> There's two:
> 
> https://github.com/dj1ch/minigotchi
> and 
> https://github.com/dj1ch/minigotchi-ESP32
> 
> The first one is for ESP8266 boards, and the second one (the repo this issue is posted on) is for ESP32. It looks like you downloaded the ESP8266 one, but you want the ESP32 one.
> 
> Try downloading the source from this repo and trying with that instead

Thank you very much for the help, I'm already fixing it, I'll probably have more issues soon

**Comment by dj1ch** [comment]
I'll close this issue as this one is solved. Thank you @matrix224
